version: '3.3'

services:
  database_pg:
    container_name: database_pg
    image: postgres:13.0
    volumes:
      - .db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 55555:5432
    networks:
      - database_api_network
    restart: always

  database_api:
    container_name: database_api
    env_file:
      - ./.env
    # environment:
    #  - POSTGRES_PATH=${POSTGRES_PRE_PATH}${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_}
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5555:8080
    depends_on:
      - database_pg
    networks:
      - database_api_network

networks:
  database_api_network:
    driver: bridge
